version: "3"

services:
  backend-pizzaria:
    container_name: backend-pizzaria
    build: ./
    env_file:
      - .env
    environment:
      - DB_HOST=db
    ports: 
      - 8000:8000
    volumes:
      - "./src:/app/src"
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: db-pizzaria
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=pizzaria
    ports:
      - 5432:5432
